print('-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-')
t = input('digite qualquer coisa: ')
print('-=--=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-')
print(f'"{t}" é...')
print(f'do tipo primitivo {type(t)}')
print(f'numérico? {t.isnumeric()}')
print(f'alfabético? {t.isalpha()}')
print(f'alfanumérico? {t.isalnum()}')
print(f'digito? {t.isdigit()}')
print(f'decimal? {t.isdecimal()}')
print(f'em letras minúsculas? {t.islower()}')
print(f'em letras maiusculas? {t.isupper()}')
print(f'espaço? {t.isspace()}')
print(f'capitalizada? {t.istitle()}')
